# Generated by Django 4.1.7 on 2023-05-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login", "0002_sendemail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SendEmail",
        ),
        migrations.AddField(
            model_name="customuser",
            name="state",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
