# Generated by Django 4.1.7 on 2023-05-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Login", "0003_delete_sendemail_customuser_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="appNum",
            field=models.IntegerField(null=True),
        ),
    ]
