# Generated by Django 4.1.7 on 2023-03-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('gradYear', models.CharField(max_length=200)),
                ('gpa', models.CharField(max_length=4)),
                ('longAns', models.CharField(max_length=100000)),
            ],
        ),
    ]
