# Generated by Django 4.1.5 on 2023-05-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('courseName', models.CharField(max_length=100)),
                ('courseCode', models.CharField(max_length=100)),
                ('courseDescription', models.CharField(max_length=1000)),
                ('building', models.CharField(choices=[('245 Beacon', '245 Beacon'), ('Gasson Hall', 'Gasson Hall'), ('Stokes Hall', 'Stokes Hall'), ('Fulton Hall', 'Fulton Hall'), ('Lyons Hall', 'Lyons Hall'), ("O'Neill", "O'Neill"), ('Higgins Hall', 'Higgins Hall')], max_length=100, null=True)),
                ('days', models.CharField(choices=[('M/W/F', 'M/W/F'), ('T/Th', 'T/Th'), ('M/W', 'M/W'), ('M', 'M'), ('T', 'T'), ('W', 'W'), ('Th', 'Th'), ('F', 'F')], max_length=100, null=True)),
                ('time', models.CharField(choices=[('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('1:00', '1:00'), ('1:30', '1:30'), ('2:00', '2:00'), ('2:30', '2:30'), ('3:00', '3:00'), ('3:30', '3:30'), ('4:00', '4:00'), ('4:30', '4:30'), ('5:00', '5:00'), ('5:30', '5:30'), ('6:00', '6:00'), ('6:30', '6:30'), ('6:00', '6:00')], max_length=100, null=True)),
                ('duration', models.CharField(choices=[('0:50', '0:50'), ('1:15', '1:15'), ('2:30', '2:30')], max_length=100, null=True)),
                ('numTAs', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=100, null=True)),
                ('gradingType', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True)),
                ('requiredOH', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=100, null=True)),
                ('discussion', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True)),
                ('discussion_day', models.CharField(choices=[('N/A', 'N/A'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=100, null=True)),
                ('discussion_time', models.CharField(choices=[('N/A', 'N/A'), ('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('1:00', '1:00'), ('1:30', '1:30'), ('2:00', '2:00'), ('2:30', '2:30'), ('3:00', '3:00'), ('3:30', '3:30'), ('4:00', '4:00'), ('4:30', '4:30'), ('5:00', '5:00'), ('5:30', '5:30'), ('6:00', '6:00'), ('6:30', '6:30'), ('7:00', '7:00')], max_length=100, null=True)),
                ('fulfilled', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], max_length=100, null=True)),
                ('extra_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('gradYear', models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], max_length=50, null=True)),
                ('gpa', models.CharField(max_length=4)),
                ('longAns', models.CharField(max_length=100000)),
            ],
        ),
    ]
