# Generated by Django 4.1.7 on 2023-03-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('gradYear', models.CharField(max_length=200)),
                ('gpa', models.CharField(max_length=4)),
                ('longAns', models.CharField(max_length=100000)),
                ('role', models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], max_length=50, null=True)),
            ],
        ),
    ]
