# Generated by Django 4.1.7 on 2023-03-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_studentapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('courseName', models.CharField(max_length=100)),
                ('courseCode', models.CharField(max_length=100)),
                ('instructorName', models.CharField(max_length=100)),
                ('courseDescription', models.CharField(max_length=1000)),
                ('building', models.CharField(max_length=100)),
                ('discussion', models.CharField(max_length=100)),
                ('numTAs', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='role',
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='gradYear',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], max_length=50, null=True),
        ),
    ]
