# Generated by Django 4.1.7 on 2023-05-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0002_studentapplication_coursename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseadd",
            name="fulfilled",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
