# Generated by Django 4.1.5 on 2023-04-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_courseadd_delete_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('class_day', models.CharField(max_length=100)),
                ('class_time', models.CharField(max_length=100)),
                ('instructor_first_name', models.CharField(max_length=100)),
                ('instructor_last_name', models.CharField(max_length=100)),
                ('num_ta', models.CharField(max_length=100)),
                ('discussion_field', models.CharField(max_length=100)),
                ('discussion_day', models.CharField(max_length=100)),
                ('discussion_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CourseAdd',
        ),
    ]
