# Generated by Django 4.1.7 on 2023-05-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0003_alter_courseadd_fulfilled"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentapplication",
            name="instructor",
            field=models.CharField(default="", max_length=100000),
            preserve_default=False,
        ),
    ]
