# Generated by Django 4.1.7 on 2023-05-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0004_studentapplication_instructor"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseadd",
            name="instructor",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
