# Generated by Django 4.1.5 on 2023-04-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_addcourse_delete_courseadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('courseName', models.CharField(max_length=100)),
                ('courseCode', models.CharField(max_length=100)),
                ('instructorName', models.CharField(max_length=100)),
                ('courseDescription', models.CharField(max_length=1000)),
                ('building', models.CharField(max_length=100)),
                ('discussion', models.CharField(max_length=100)),
                ('numTAs', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AddCourse',
        ),
    ]
