# Generated by Django 4.2 on 2023-04-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_courseadd_delete_addcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseadd',
            name='instructorName',
        ),
        migrations.AddField(
            model_name='courseadd',
            name='days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseadd',
            name='building',
            field=models.CharField(choices=[('245 Beacon', '245 Beacon'), ('Gasson Hall', 'Gasson Hall'), ('Stokes Hall', 'Stokes Hall'), ('Fulton Hall', 'Fulton Hall'), ('Lyons Hall', 'Lyons Hall'), ("O'Neill", "O'Neill"), ('Higgins Hall', 'Higgins Hall')], max_length=100, null=True),
        ),
    ]
