# Generated by Django 4.1.5 on 2023-05-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_courseadd_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseadd',
            name='currTAs',
            field=models.IntegerField(null=True),
        ),
    ]
