# Generated by Django 4.2 on 2023-04-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_remove_courseadd_instructorname_courseadd_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseadd',
            name='discussion_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courseadd',
            name='discussion_time',
            field=models.CharField(choices=[('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('1:00', '1:00'), ('1:30', '1:30'), ('2:00', '2:00'), ('2:30', '2:30'), ('3:00', '3:00'), ('3:30', '3:30'), ('4:00', '4:00'), ('4:30', '4:30'), ('5:00', '5:00'), ('5:30', '5:30'), ('6:00', '6:00'), ('6:30', '6:30'), ('6:00', '6:00')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courseadd',
            name='duration',
            field=models.CharField(choices=[('0:50', '0:50'), ('1:15', '1:15'), ('2:30', '2:30')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courseadd',
            name='time',
            field=models.CharField(choices=[('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('1:00', '1:00'), ('1:30', '1:30'), ('2:00', '2:00'), ('2:30', '2:30'), ('3:00', '3:00'), ('3:30', '3:30'), ('4:00', '4:00'), ('4:30', '4:30'), ('5:00', '5:00'), ('5:30', '5:30'), ('6:00', '6:00'), ('6:30', '6:30'), ('6:00', '6:00')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseadd',
            name='discussion',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseadd',
            name='numTAs',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=100, null=True),
        ),
    ]
