# Generated by Django 4.1.7 on 2023-05-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0008_alter_studentapplication_results"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseadd",
            name="courseState",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
