# Generated by Django 4.1.7 on 2023-05-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0009_courseadd_coursestate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentapplication",
            name="email",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
