# Generated by Django 4.1.7 on 2023-05-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0010_alter_studentapplication_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseadd",
            name="instructor",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
