# Generated by Django 4.1.7 on 2023-04-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Application", "0010_alter_courseadd_discussion_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentapplication",
            name="courseCode",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
