# Generated by Django 4.2 on 2023-05-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0012_courseadd_namesoftas'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseadd',
            name='roomNumber',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
