# Generated by Django 4.2 on 2023-04-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0012_remove_studentapplication_coursecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseadd',
            name='extra_info',
            field=models.CharField(default='Extra Information', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseadd',
            name='gradingType',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='courseadd',
            name='requiredOH',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=100, null=True),
        ),
    ]
