# Generated by Django 4.2 on 2023-05-15 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0013_courseadd_roomnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseadd',
            name='roomNumber',
        ),
    ]
